SCREEN_WIDTH = 480
SCREEN_HEIGHT = 270
SCREEN_TITLE = "Dungeons and Directories"
FRAMERATE = 1/60

PLAYER_SIZE = 10
PLAYER_MOVE_FORCE = 100
PLAYER_START = [SCREEN_WIDTH/2, SCREEN_HEIGHT/2]

# used by tools
MAX_ID_ITERATIONS = 30

# used by engine.Engine
LAYERS = 3
